---
- name: setup azure demo environment
  hosts: localhost
  gather_facts: false
  become: true

  tasks:

    - name: Add project
      ansible.controller.project:
        name: "Azure Demos Project"
        description: "This is from github.com/ansible-cloud"
        organization: "Default"
        state: present
        scm_type: git
        scm_url: https://github.com/ansible-cloud/azure-demos
        default_environment: "ee-cloud-services"

    - name: create job template
      ansible.controller.job_template:
        name: "{{ item.name }}"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        project: "Azure Demos Project"
        extra_vars:
          resource_group_name: "azure-demo"
          region: "eastus"
          vnet_cidr: "10.0.0.0/16"
          subnet_cidr: "10.0.1.0/24"
          vnet_name: "demo_vnet"
          subnet_name: "demo_subnet"
          network_sec_group_name: "demo_sec_group"
          win_vm_name: "WIN-ansible"
          win_vm_size: "Standard_DS1_v2"
          win_vm_sku: "2022-Datacenter"
          win_public_ip_name: "win_demo_ip"
          win_nic_name: "win_demo_nic"
          win_admin_user: "azureuser"
          win_admin_password: "ansible123!"
        playbook: "project/{{ item.playbook }}"
        credentials:
          - "Microsoft Azure Resource Manager"
        state: "present"
      with_items:
        - { playbook: 'create_resource_group.yml', name: 'Create Azure Resource Group' }
        - { playbook: 'create_windows_vm_demo.yml', name: 'Create Windows Server 2022 VM' }
        - { playbook: 'destroy_resource_group.yml', name: 'Destroy Azure Resource Group' }

    - name: create job template
      ansible.controller.job_template:
        name: "{{ item.name }}"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        project: "Azure Demos Project"
        extra_vars:
          resource_group_name: "azure-demo"
          region: "eastus"
          vnet_cidr: "10.0.0.0/16"
          subnet_cidr: "10.0.1.0/24"
          vnet_name: "demo_vnet"
          subnet_name: "demo_subnet"
          network_sec_group_name: "demo_sec_group"
          win_vm_name: "WIN-ansible"
          win_vm_size: "Standard_DS1_v2"
          win_vm_sku: "2022-Datacenter"
          win_public_ip_name: "win_demo_ip"
          win_nic_name: "win_demo_nic"
          win_admin_user: "azureuser"
          win_admin_password: "ansible123!"
        playbook: "workflow/{{ item.playbook }}"
        credentials:
          - "Microsoft Azure Resource Manager"
        state: "present"
      with_items:
        - { playbook: '01-create_resource_group.yml', name: 'WF-01-Create Resource Group' }
        - { playbook: '02-create_virtual_network.yml', name: 'WF-02-Create Virtual Network' }
        - { playbook: '03-add_subnet.yml', name: 'WF-03-Add Subnet' }
        - { playbook: '04-create_public_ip_address.yml', name: 'WF-04-Create Public IP Address' }
        - { playbook: '05-create_network_security_group.yml', name:  'WF-05-Create Network Security Group' }
        - { playbook: '06-create_virtual_network_interface_card.yml', name: 'WF-06-Create Virtual Network Interface Card' }
        - { playbook: '07-create_windows_2022_vm.yml', name: 'WF-07-Create Windows 2022 Virtual Machine' }

    - name: create workflow template
      ansible.controller.workflow_job_template:
        name: "network-infra-deploy-config-windows2022"
        organization: "Default"
        schema:
        - identifier: "WF-01-Create Resource Group"
          unified_job_template:
            name: "WF-01-Create Resource Group"
              organization:
                name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "WF-02-Create Virtual Network"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "WF-02-Create Virtual Network"
          unified_job_template:
            name: "WF-02-Create Virtual Network"
              organization:
                name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "WF-03-Add Subnet"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "WF-03-Add Subnet"
          unified_job_template:
            name: "WF-03-Add Subnet"
              organization:
                name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "WF-04-Create Public IP Address"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "WF-04-Create Public IP Address"
          unified_job_template:
            name: "WF-04-Create Public IP Address"
              organization:
                name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "WF-05-Create Network Security Group"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "WF-05-Create Network Security Group"
          unified_job_template:
            name: "WF-05-Create Network Security Group"
              organization:
                name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "WF-06-Create Virtual Network Interface Card"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "WF-06-Create Virtual Network Interface Card"
          unified_job_template:
            name: "WF-06-Create Virtual Network Interface Card"
              organization:
                name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "WF-07-Create Windows 2022 Virtual Machine"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "WF-07-Create Windows 2022 Virtual Machine"
          unified_job_template:
            name: "WF-07-Create Windows 2022 Virtual Machine"
              organization:
                name: "Default"              
            type: job_template
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: []
